# Project information
site_name: IoT Workshop

site_description: 'Internet of Things Workshop voor C.S.V. Alpha'
site_author: 'Ruben Smit en Hilke van den Born'

# Copyright
copyright: Copyright &copy; 2021 C.S.V. Alpha

# Repo
repo_url: https://github.com/csvalpha/iot-workshop
repo_name: csvalpha/iot-workshop

# Congiguration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: preference
  language: nl
plugins:
  - search:
      lang: nl
  - with-pdf:
      #author: WHO
      #copyright: ANY TEXT
      #
      #cover: false
      # back_cover: true
      cover_title: Internet of Things Workshop
      cover_subtitle: Solderen en Programmeren
      cover_logo: assets/images/finished-ledring.jpg
      #custom_template_path: TEMPLATES PATH
      #
      toc_title: Inhoudsopgave
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: pdf/IoT-Workshop-Handleiding.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true

# Navigation
nav:
  - Voorbereiding: 'index.md'
  - Hardware:
    - Hardware overzicht: 'hardware/index.md'
    - Ledring: 'hardware/ledring.md'
    - Voltage divider: 'hardware/voltage-divider.md'
    - Potentiometer: 'hardware/potentiometer.md'
    - Pull-down resistor: 'hardware/pull-down-resistor.md'
    - Knopje: 'hardware/knopje.md'
  - Behuizing: 'behuizing.md'
  - Software: 
    - Arduino IDE: 'software/index.md'
    - Introductie: 'software/introductie.md'
    - Digitale I/O: 'software/digitale-io.md'
    - Analoge input: 'software/analoge-input.md'
    - Ledring: 'software/ledring.md'
    - Wifi: 'software/wifi.md'
    - Datum en Tijd: 'software/datum-en-tijd.md'
    - Webservices: 'software/webservices.md'
  - Projecten:
    - Projectoverzicht: 'projecten/index.md'
    - Nachtlampje: 'projecten/nachtlampje.md'
    - Wakeuplight: 'projecten/wakeuplight.md'
    - Klok: 'projecten/klok.md'
    - Agenda: 'projecten/agenda.md'
  - Probleemoplosser: 'probleemoplosser.md'
