# Project information
site_name: IoT Workshop

site_description: 'Internet of Things Workshop voor C.S.V. Alpha'
site_author: 'C.S.V. Alpha'

# Copyright
copyright: Copyright &copy; 2021 C.S.V. Alpha

# Repo
repo_url: https://github.com/csvalpha/iot-workshop
repo_name: csvalpha/iot-workshop

# Congiguration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
  palette:
    scheme: preference
  language: nl
plugins:
  - search:
      lang: nl
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true

# Navigation
nav:
  - Voorbereiding: 'index.md'
  - Hardware:
    - Hardware overzicht: 'hardware/index.md'
    - Ledring: 'hardware/ledring.md'
    - Voltage divider: 'hardware/voltage-divider.md'
    - Potentiometer: 'hardware/potentiometer.md'
    - Pull-down resistor: 'hardware/pull-down-resistor.md'
    - Knopje: 'hardware/knopje.md'
  - Behuizing: 'behuizing.md'
  - Software: 
    - Arduino IDE: 'software/index.md'
    - Introductie: 'software/introductie.md'
    - Digitale I/O: 'software/digitale-io.md'
    - Analoge input: 'software/analoge-input.md'
    - Ledring: 'software/ledring.md'
    - Wifi: 'software/wifi.md'
    - Datum en Tijd: 'software/datum-en-tijd.md'
    - Webservices: 'software/webservices.md'
  - Projecten:
    - Projectoverzicht: 'projecten/index.md'
    - Nachtlampje: 'projecten/nachtlampje.md'
    - Wakeuplight: 'projecten/wakeuplight.md'
    - Klok: 'projecten/klok.md'
    - Agenda: 'projecten/agenda.md'
  - Probleemoplosser: 'probleemoplosser.md'
